on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: node:16-buster
            tag: node-16
          - image: node:14-buster
            tag: node-14
          - image: node:12-buster
            tag: node-12
    steps:
      - uses: actions/checkout@v2
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,prefix=${{ matrix.tag }}--
            type=ref,event=pr,prefix=${{ matrix.tag }}--
            type=sha,prefix=${{ matrix.tag }}--sha-
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: images
          platforms: linux/amd64
          build-args: |
            FROM_IMAGE=${{ matrix.image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
