on:
  pull_request:
    paths:
      - images/**
      - .github/workflows/build-and-push.yaml
    branches:
      - main
  push:
    paths:
      - images/**
      - .github/workflows/build-and-push.yaml
    branches:
      - main

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - node-16
          - node-14
          - node-12
          - ruby-3-0
          - ruby-2-7
          - ruby-2-6
          - rust
    steps:
      - uses: actions/checkout@v2
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,prefix=${{ matrix.tag }}--
            type=ref,event=pr,prefix=${{ matrix.tag }}--pr-
            type=sha,prefix=${{ matrix.tag }}--sha-
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: images/${{ matrix.tag }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
